config/routes.rb
Rails.application.routes.draw do
  get 'user_dashboard/index'
  get 'event_registrations/new'
  get 'event_registrations/create'
  resources :line_items
  resources :carts
  get 'gallery/index'
  get 'gallery/checkout'
  post 'gallery/checkout'
  get 'gallery/search'
  resources :registrations, except: [:new, :create]  # Regular CRUD routes
  get "/dashboard", to: "dashboard#index", as: "dashboard"
  get "/dashboard/index"
  resources :events
  get 'home/index', to: "home#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  
  resources :event_registrations, only: [:new, :create]

  
  Rails.application.routes.draw do
  get 'user_dashboard/index'
    resources :event_registrations, only: [:new, :create]
    resource :cart, only: [:show, :destroy]
    get "/checkout", to: "checkout#show"
  end
  # post "gallery/checkout", to: "payments#create", as: :create_payment
  get "gallery/purchase_complete"
  get "gallery/purchase_complete_final"
  get "gallery/final_checkout"
  get 'user_dashboard', to: 'user_dashboard#index'


  Rails.application.routes.draw do
  get 'user_dashboard/index'
    resources :gallery do
      collection do
        get 'final_checkout'   # Route to display final payment page
        post 'final_checkout'  # Route to process final payment
      end
    end
  end
  
  get 'data/registered_users', to: 'data#registered_users'


  
  
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :event
  has_one_attached :event_image

  def total_price
    event.price * self.quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json

  def create
    @cart = current_cart
    event = Event.find(params[:event_id])
  
    # Ensure the quantity is properly received from params
    quantity = params[:quantity].present? ? params[:quantity].to_i : 1
  
    # Find existing line_item or create a new one
    @line_item = @cart.line_items.find_or_initialize_by(event_id: event.id)
  
    # Update the quantity correctly
    @line_item.quantity += quantity if @line_item.persisted?
    @line_item.quantity = quantity unless @line_item.persisted?
  
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to cart_path(@cart), notice: "Added to cart successfully!" }
      else
        format.html { redirect_to events_path, alert: "Failed to add to cart." }
      end
    end
  end
  
  
  


  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy!

    respond_to do |format|
      format.html { redirect_to line_items_path, status: :see_other, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:cart_id, :store_id, :quantity)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.label :event_id, style: "display: block" %>
    <%= form.text_field :event_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
<td class="col-quantity"><%= line_item.quantity %></td>
<td class="col-event"><%= image_tag line_item.event.event_image, class: "featured__image" %></td>
<td class="col-event"><%= line_item.event.title %></td>
<td class="col-price"><%= number_to_indian_currancy(line_item.event.price) %></td>
<td class="col-total"><%= number_to_indian_currancy(line_item.total_price) %></td>
</tr>

app/views/line_items/edit.html.erb
<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show this line item", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New line item", new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @line_item %>

<div>
  <%= link_to "Edit this line item", edit_line_item_path(@line_item) %> |
  <%= link_to "Back to line items", line_items_path %>

  <%= button_to "Destroy this line item", @line_item, method: :delete %>
</div>